
import ListMaterial from "@/components/ListMaterial";
import { AuthContext } from "@/contexts/authContext";
import styles from "@/styles/Home.module.css";
import { Inter } from "next/font/google";
import Head from "next/head";
import { useContext } from "react";
import { LIST_CATEGORIES } from "@/requetes/queries/category.queries";
import { useQuery } from "@apollo/client";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  console.log('LISTCATEGORIES', LIST_CATEGORIES)
  const { user } = useContext(AuthContext);

  return (
    <>
      <Head>
        <title>SnowWild</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        
        <div className={styles.description}>
          <ListMaterial />
        </div>
      </main>
    </>
  );
}